cashcow:
  version: "1.0"
  database: cashcow.db
  
  # Entity type configurations
  entity_types:
    employee:
      required_fields: [salary]
      calculators: [salary_calc, equity_calc, overhead_calc]
      default_overhead_multiplier: 1.3
      
    grant:
      required_fields: [amount]
      calculators: [milestone_calc, disbursement_calc]
      
    investment:
      required_fields: [amount]
      calculators: [disbursement_calc]
      
    sale:
      required_fields: [amount]
      calculators: [revenue_calc]
      
    service:
      required_fields: [monthly_amount]
      calculators: [recurring_calc]
      
    facility:
      required_fields: [monthly_cost]
      calculators: [recurring_calc, utilities_calc]
      
    software:
      required_fields: [monthly_cost]
      calculators: [recurring_calc]
      
    equipment:
      required_fields: [cost, purchase_date]
      calculators: [one_time_calc, depreciation_calc]
      
    project:
      required_fields: [total_budget]
      calculators: [milestone_calc, burn_calc]
      
    # Cap table entity types
    shareholder:
      required_fields: [shareholder_type, total_shares, share_class]
      calculators: [ownership_percentage, voting_power, dilution_impact]
      directory: "captable/shareholders"
      validation_rules:
        - total_shares_positive
        - valid_shareholder_type
        - vesting_consistency
      
    share_class:
      required_fields: [class_name, shares_authorized]
      calculators: [utilization_calc, preference_coverage, conversion_value]
      directory: "captable/share_classes"
      validation_rules:
        - shares_authorized_positive
        - outstanding_within_authorized
        - valid_liquidation_preference
        
    funding_round:
      required_fields: [round_type, amount_raised]
      calculators: [dilution_calc, valuation_impact, ownership_calc]
      directory: "captable/funding_rounds"
      validation_rules:
        - amount_raised_positive
        - valuation_consistency
        - share_math_consistency
  
  # KPI configurations
  kpis:
    - name: runway
      description: "Months until cash reaches zero"
      category: financial
    - name: burn_rate
      description: "Monthly cash consumption"
      category: financial
    - name: revenue_growth
      description: "Month-over-month revenue growth percentage"
      category: revenue
    - name: rd_percentage
      description: "R&D spend as percentage of total expenses"
      category: operational
    - name: revenue_per_employee
      description: "Revenue divided by active employees"
      category: efficiency
    - name: cac
      description: "Customer acquisition cost"
      category: sales
      
    # Cap table KPIs
    - name: founder_ownership
      description: "Founder ownership percentage (fully diluted)"
      category: ownership
    - name: employee_ownership
      description: "Employee ownership percentage (fully diluted)"
      category: ownership
    - name: liquidation_overhang
      description: "Liquidation preference overhang multiple"
      category: ownership
    - name: option_pool_remaining
      description: "Remaining option pool percentage"
      category: ownership
    - name: voting_control_concentration
      description: "Voting control concentration (HHI index)"
      category: governance
    - name: board_independence
      description: "Independent board member ratio"
      category: governance
    - name: anti_dilution_exposure
      description: "Exposure to anti-dilution adjustments"
      category: governance
  
  # Reporting configurations
  reporting:
    default_forecast_months: 24
    chart_style: seaborn
    output_formats: [csv, json, html]
    
  # Scenario configurations
  scenarios:
    default: baseline
    sensitivity_variables:
      - revenue_growth_rate
      - hiring_rate
      - overhead_multiplier
      - grant_success_rate